/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dtt.portal.dao.vbpq.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VanBanPhapQuy service. Represents a row in the &quot;EPORTAL_VANBAN&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.dtt.portal.dao.vbpq.model.impl.VanBanPhapQuyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.dtt.portal.dao.vbpq.model.impl.VanBanPhapQuyImpl}.
 * </p>
 *
 * @author HuyMQ
 * @see VanBanPhapQuy
 * @see com.dtt.portal.dao.vbpq.model.impl.VanBanPhapQuyImpl
 * @see com.dtt.portal.dao.vbpq.model.impl.VanBanPhapQuyModelImpl
 * @generated
 */
public interface VanBanPhapQuyModel extends BaseModel<VanBanPhapQuy> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a van ban phap quy model instance should use the {@link VanBanPhapQuy} interface instead.
	 */

	/**
	 * Returns the primary key of this van ban phap quy.
	 *
	 * @return the primary key of this van ban phap quy
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this van ban phap quy.
	 *
	 * @param primaryKey the primary key of this van ban phap quy
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this van ban phap quy.
	 *
	 * @return the ID of this van ban phap quy
	 */
	public long getId();

	/**
	 * Sets the ID of this van ban phap quy.
	 *
	 * @param id the ID of this van ban phap quy
	 */
	public void setId(long id);

	/**
	 * Returns the ma van ban of this van ban phap quy.
	 *
	 * @return the ma van ban of this van ban phap quy
	 */
	@AutoEscape
	public String getMaVanBan();

	/**
	 * Sets the ma van ban of this van ban phap quy.
	 *
	 * @param maVanBan the ma van ban of this van ban phap quy
	 */
	public void setMaVanBan(String maVanBan);

	/**
	 * Returns the ngay tao of this van ban phap quy.
	 *
	 * @return the ngay tao of this van ban phap quy
	 */
	public Date getNgayTao();

	/**
	 * Sets the ngay tao of this van ban phap quy.
	 *
	 * @param ngayTao the ngay tao of this van ban phap quy
	 */
	public void setNgayTao(Date ngayTao);

	/**
	 * Returns the ngay sua of this van ban phap quy.
	 *
	 * @return the ngay sua of this van ban phap quy
	 */
	public Date getNgaySua();

	/**
	 * Sets the ngay sua of this van ban phap quy.
	 *
	 * @param ngaySua the ngay sua of this van ban phap quy
	 */
	public void setNgaySua(Date ngaySua);

	/**
	 * Returns the nguoi tao of this van ban phap quy.
	 *
	 * @return the nguoi tao of this van ban phap quy
	 */
	@AutoEscape
	public String getNguoiTao();

	/**
	 * Sets the nguoi tao of this van ban phap quy.
	 *
	 * @param nguoiTao the nguoi tao of this van ban phap quy
	 */
	public void setNguoiTao(String nguoiTao);

	/**
	 * Returns the nguoi sua of this van ban phap quy.
	 *
	 * @return the nguoi sua of this van ban phap quy
	 */
	@AutoEscape
	public String getNguoiSua();

	/**
	 * Sets the nguoi sua of this van ban phap quy.
	 *
	 * @param nguoiSua the nguoi sua of this van ban phap quy
	 */
	public void setNguoiSua(String nguoiSua);

	/**
	 * Returns the trich yeu of this van ban phap quy.
	 *
	 * @return the trich yeu of this van ban phap quy
	 */
	@AutoEscape
	public String getTrichYeu();

	/**
	 * Sets the trich yeu of this van ban phap quy.
	 *
	 * @param trichYeu the trich yeu of this van ban phap quy
	 */
	public void setTrichYeu(String trichYeu);

	/**
	 * Returns the co quan ban hanh of this van ban phap quy.
	 *
	 * @return the co quan ban hanh of this van ban phap quy
	 */
	public long getCoQuanBanHanh();

	/**
	 * Sets the co quan ban hanh of this van ban phap quy.
	 *
	 * @param coQuanBanHanh the co quan ban hanh of this van ban phap quy
	 */
	public void setCoQuanBanHanh(long coQuanBanHanh);

	/**
	 * Returns the loai van ban of this van ban phap quy.
	 *
	 * @return the loai van ban of this van ban phap quy
	 */
	public long getLoaiVanBan();

	/**
	 * Sets the loai van ban of this van ban phap quy.
	 *
	 * @param loaiVanBan the loai van ban of this van ban phap quy
	 */
	public void setLoaiVanBan(long loaiVanBan);

	/**
	 * Returns the linh vuc van ban of this van ban phap quy.
	 *
	 * @return the linh vuc van ban of this van ban phap quy
	 */
	public long getLinhVucVanBan();

	/**
	 * Sets the linh vuc van ban of this van ban phap quy.
	 *
	 * @param linhVucVanBan the linh vuc van ban of this van ban phap quy
	 */
	public void setLinhVucVanBan(long linhVucVanBan);

	/**
	 * Returns the ngay ban hanh of this van ban phap quy.
	 *
	 * @return the ngay ban hanh of this van ban phap quy
	 */
	public Date getNgayBanHanh();

	/**
	 * Sets the ngay ban hanh of this van ban phap quy.
	 *
	 * @param ngayBanHanh the ngay ban hanh of this van ban phap quy
	 */
	public void setNgayBanHanh(Date ngayBanHanh);

	/**
	 * Returns the ngay co hieu luc of this van ban phap quy.
	 *
	 * @return the ngay co hieu luc of this van ban phap quy
	 */
	public Date getNgayCoHieuLuc();

	/**
	 * Sets the ngay co hieu luc of this van ban phap quy.
	 *
	 * @param ngayCoHieuLuc the ngay co hieu luc of this van ban phap quy
	 */
	public void setNgayCoHieuLuc(Date ngayCoHieuLuc);

	/**
	 * Returns the ngay het hieu luc of this van ban phap quy.
	 *
	 * @return the ngay het hieu luc of this van ban phap quy
	 */
	public Date getNgayHetHieuLuc();

	/**
	 * Sets the ngay het hieu luc of this van ban phap quy.
	 *
	 * @param ngayHetHieuLuc the ngay het hieu luc of this van ban phap quy
	 */
	public void setNgayHetHieuLuc(Date ngayHetHieuLuc);

	/**
	 * Returns the nguoi ky of this van ban phap quy.
	 *
	 * @return the nguoi ky of this van ban phap quy
	 */
	@AutoEscape
	public String getNguoiKy();

	/**
	 * Sets the nguoi ky of this van ban phap quy.
	 *
	 * @param nguoiKy the nguoi ky of this van ban phap quy
	 */
	public void setNguoiKy(String nguoiKy);

	/**
	 * Returns the van ban thay the of this van ban phap quy.
	 *
	 * @return the van ban thay the of this van ban phap quy
	 */
	public long getVanBanThayThe();

	/**
	 * Sets the van ban thay the of this van ban phap quy.
	 *
	 * @param vanBanThayThe the van ban thay the of this van ban phap quy
	 */
	public void setVanBanThayThe(long vanBanThayThe);

	/**
	 * Returns the group ID of this van ban phap quy.
	 *
	 * @return the group ID of this van ban phap quy
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this van ban phap quy.
	 *
	 * @param groupId the group ID of this van ban phap quy
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the status of this van ban phap quy.
	 *
	 * @return the status of this van ban phap quy
	 */
	public int getStatus();

	/**
	 * Sets the status of this van ban phap quy.
	 *
	 * @param status the status of this van ban phap quy
	 */
	public void setStatus(int status);

	/**
	 * Returns the status by date of this van ban phap quy.
	 *
	 * @return the status by date of this van ban phap quy
	 */
	public Date getStatusByDate();

	/**
	 * Sets the status by date of this van ban phap quy.
	 *
	 * @param statusByDate the status by date of this van ban phap quy
	 */
	public void setStatusByDate(Date statusByDate);

	/**
	 * Returns the status by user ID of this van ban phap quy.
	 *
	 * @return the status by user ID of this van ban phap quy
	 */
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this van ban phap quy.
	 *
	 * @param statusByUserId the status by user ID of this van ban phap quy
	 */
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this van ban phap quy.
	 *
	 * @return the status by user uuid of this van ban phap quy
	 * @throws SystemException if a system exception occurred
	 */
	public String getStatusByUserUuid() throws SystemException;

	/**
	 * Sets the status by user uuid of this van ban phap quy.
	 *
	 * @param statusByUserUuid the status by user uuid of this van ban phap quy
	 */
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this van ban phap quy.
	 *
	 * @return the status by user name of this van ban phap quy
	 */
	@AutoEscape
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this van ban phap quy.
	 *
	 * @param statusByUserName the status by user name of this van ban phap quy
	 */
	public void setStatusByUserName(String statusByUserName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VanBanPhapQuy vanBanPhapQuy);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VanBanPhapQuy> toCacheModel();

	@Override
	public VanBanPhapQuy toEscapedModel();

	@Override
	public VanBanPhapQuy toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}