/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dtt.portal.dao.vbpq.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the AttachFile service. Represents a row in the &quot;EPORTAL_ATTACHFILE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.dtt.portal.dao.vbpq.model.impl.AttachFileModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.dtt.portal.dao.vbpq.model.impl.AttachFileImpl}.
 * </p>
 *
 * @author HuyMQ
 * @see AttachFile
 * @see com.dtt.portal.dao.vbpq.model.impl.AttachFileImpl
 * @see com.dtt.portal.dao.vbpq.model.impl.AttachFileModelImpl
 * @generated
 */
public interface AttachFileModel extends BaseModel<AttachFile> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a attach file model instance should use the {@link AttachFile} interface instead.
	 */

	/**
	 * Returns the primary key of this attach file.
	 *
	 * @return the primary key of this attach file
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this attach file.
	 *
	 * @param primaryKey the primary key of this attach file
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this attach file.
	 *
	 * @return the ID of this attach file
	 */
	public long getId();

	/**
	 * Sets the ID of this attach file.
	 *
	 * @param id the ID of this attach file
	 */
	public void setId(long id);

	/**
	 * Returns the van ban ID of this attach file.
	 *
	 * @return the van ban ID of this attach file
	 */
	public long getVanBanId();

	/**
	 * Sets the van ban ID of this attach file.
	 *
	 * @param vanBanId the van ban ID of this attach file
	 */
	public void setVanBanId(long vanBanId);

	/**
	 * Returns the file ID of this attach file.
	 *
	 * @return the file ID of this attach file
	 */
	public long getFileId();

	/**
	 * Sets the file ID of this attach file.
	 *
	 * @param fileId the file ID of this attach file
	 */
	public void setFileId(long fileId);

	/**
	 * Returns the file link of this attach file.
	 *
	 * @return the file link of this attach file
	 */
	@AutoEscape
	public String getFileLink();

	/**
	 * Sets the file link of this attach file.
	 *
	 * @param fileLink the file link of this attach file
	 */
	public void setFileLink(String fileLink);

	/**
	 * Returns the file name of this attach file.
	 *
	 * @return the file name of this attach file
	 */
	@AutoEscape
	public String getFileName();

	/**
	 * Sets the file name of this attach file.
	 *
	 * @param fileName the file name of this attach file
	 */
	public void setFileName(String fileName);

	/**
	 * Returns the file size of this attach file.
	 *
	 * @return the file size of this attach file
	 */
	@AutoEscape
	public String getFileSize();

	/**
	 * Sets the file size of this attach file.
	 *
	 * @param fileSize the file size of this attach file
	 */
	public void setFileSize(String fileSize);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AttachFile attachFile);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AttachFile> toCacheModel();

	@Override
	public AttachFile toEscapedModel();

	@Override
	public AttachFile toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}