/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dtt.portal.dao.vbpq.model.impl;

import com.dtt.portal.dao.vbpq.model.LinhVucVanBan;
import com.dtt.portal.dao.vbpq.service.LinhVucVanBanLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the LinhVucVanBan service. Represents a row in the &quot;EPORTAL_LINHVUCVANBAN&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LinhVucVanBanImpl}.
 * </p>
 *
 * @author HuyMQ
 * @see LinhVucVanBanImpl
 * @see com.dtt.portal.dao.vbpq.model.LinhVucVanBan
 * @generated
 */
public abstract class LinhVucVanBanBaseImpl extends LinhVucVanBanModelImpl
	implements LinhVucVanBan {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a linh vuc van ban model instance should use the {@link LinhVucVanBan} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			LinhVucVanBanLocalServiceUtil.addLinhVucVanBan(this);
		}
		else {
			LinhVucVanBanLocalServiceUtil.updateLinhVucVanBan(this);
		}
	}
}