create index IX_3FCAD070 on EPORTAL_ATTACHFILE (VANBANID);

create index IX_45A28EDF on EPORTAL_COQUANBANHANH (TRANGTHAI, GROUPID);

create index IX_4E0E9BB3 on EPORTAL_LINHVUCVANBAN (TRANGTHAI, GROUPID);

create index IX_27B8E76D on EPORTAL_LOAIVANBAN (TRANGTHAI, GROUPID);

create index IX_C3936002 on EPORTAL_VANBAN (TRANGTHAI, GROUPID);