create table EPORTAL_ATTACHFILE (
	ID LONG not null primary key,
	VANBANID LONG,
	FILEID LONG,
	FILELINK VARCHAR(75) null
);

create table EPORTAL_COQUANBANHANH (
	ID LONG not null primary key,
	TEN VARCHAR(75) null,
	TRANGTHAI BOOLEAN,
	NGAYTAO DATE null,
	NGAYSUA DATE null,
	NGUOITAO VARCHAR(75) null,
	NGUOISUA VARCHAR(75) null,
	GROUPID LONG
);

create table EPORTAL_LINHVUCVANBAN (
	ID LONG not null primary key,
	TEN VARCHAR(75) null,
	TRANGTHAI BOOLEAN,
	NGAYTAO DATE null,
	NGAYSUA DATE null,
	NGUOITAO VARCHAR(75) null,
	NGUOISUA VARCHAR(75) null,
	GROUPID LONG
);

create table EPORTAL_LOAIVANBAN (
	ID LONG not null primary key,
	TEN VARCHAR(75) null,
	TRANGTHAI BOOLEAN,
	NGAYTAO DATE null,
	NGAYSUA DATE null,
	NGUOITAO VARCHAR(75) null,
	NGUOISUA VARCHAR(75) null,
	GROUPID LONG
);

create table EPORTAL_VANBAN (
	ID LONG not null primary key,
	MAVANBAN VARCHAR(75) null,
	TRANGTHAI BOOLEAN,
	NGAYTAO DATE null,
	NGAYSUA DATE null,
	NGUOITAO VARCHAR(75) null,
	NGUOISUA VARCHAR(75) null,
	COQUANBANHANH LONG,
	LOAIVANBAN LONG,
	LINHVUCVANBAN LONG,
	NGAYBANHANH DATE null,
	NGAYCOHIEULUC DATE null,
	NGAYHETHIEULUC DATE null,
	NGUOIKY VARCHAR(75) null,
	VANBANTHAYTHE LONG,
	GROUPID LONG
);