/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dtt.portal.dao.vbpq.model.impl;

import com.dtt.portal.dao.vbpq.model.VanBanPhapQuy;
import com.dtt.portal.dao.vbpq.model.VanBanPhapQuyModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the VanBanPhapQuy service. Represents a row in the &quot;EPORTAL_VANBAN&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.dtt.portal.dao.vbpq.model.VanBanPhapQuyModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VanBanPhapQuyImpl}.
 * </p>
 *
 * @author HuyMQ
 * @see VanBanPhapQuyImpl
 * @see com.dtt.portal.dao.vbpq.model.VanBanPhapQuy
 * @see com.dtt.portal.dao.vbpq.model.VanBanPhapQuyModel
 * @generated
 */
public class VanBanPhapQuyModelImpl extends BaseModelImpl<VanBanPhapQuy>
	implements VanBanPhapQuyModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a van ban phap quy model instance should use the {@link com.dtt.portal.dao.vbpq.model.VanBanPhapQuy} interface instead.
	 */
	public static final String TABLE_NAME = "EPORTAL_VANBAN";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "MAVANBAN", Types.VARCHAR },
			{ "NGAYTAO", Types.TIMESTAMP },
			{ "NGAYSUA", Types.TIMESTAMP },
			{ "NGUOITAO", Types.VARCHAR },
			{ "NGUOISUA", Types.VARCHAR },
			{ "TRICHYEU", Types.VARCHAR },
			{ "COQUANBANHANH", Types.BIGINT },
			{ "LOAIVANBAN", Types.BIGINT },
			{ "LINHVUCVANBAN", Types.BIGINT },
			{ "NGAYBANHANH", Types.TIMESTAMP },
			{ "NGAYCOHIEULUC", Types.TIMESTAMP },
			{ "NGAYHETHIEULUC", Types.TIMESTAMP },
			{ "NGUOIKY", Types.VARCHAR },
			{ "VANBANTHAYTHE", Types.BIGINT },
			{ "GROUPID", Types.BIGINT },
			{ "STATUS", Types.INTEGER },
			{ "STATUSBYDATE", Types.TIMESTAMP },
			{ "STATUSBYUSERID", Types.BIGINT },
			{ "STATUSBYUSERNAME", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table EPORTAL_VANBAN (ID LONG not null primary key,MAVANBAN VARCHAR(75) null,NGAYTAO DATE null,NGAYSUA DATE null,NGUOITAO VARCHAR(75) null,NGUOISUA VARCHAR(75) null,TRICHYEU VARCHAR(75) null,COQUANBANHANH LONG,LOAIVANBAN LONG,LINHVUCVANBAN LONG,NGAYBANHANH DATE null,NGAYCOHIEULUC DATE null,NGAYHETHIEULUC DATE null,NGUOIKY VARCHAR(75) null,VANBANTHAYTHE LONG,GROUPID LONG,STATUS INTEGER,STATUSBYDATE DATE null,STATUSBYUSERID LONG,STATUSBYUSERNAME VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table EPORTAL_VANBAN";
	public static final String ORDER_BY_JPQL = " ORDER BY vanBanPhapQuy.ngayBanHanh DESC, vanBanPhapQuy.ngayCoHieuLuc ASC";
	public static final String ORDER_BY_SQL = " ORDER BY EPORTAL_VANBAN.NGAYBANHANH DESC, EPORTAL_VANBAN.NGAYCOHIEULUC ASC";
	public static final String DATA_SOURCE = "ePortalDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.dtt.portal.dao.vbpq.model.VanBanPhapQuy"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.dtt.portal.dao.vbpq.model.VanBanPhapQuy"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.dtt.portal.dao.vbpq.model.VanBanPhapQuy"),
			true);
	public static long COQUANBANHANH_COLUMN_BITMASK = 1L;
	public static long GROUPID_COLUMN_BITMASK = 2L;
	public static long MAVANBAN_COLUMN_BITMASK = 4L;
	public static long STATUS_COLUMN_BITMASK = 8L;
	public static long NGAYBANHANH_COLUMN_BITMASK = 16L;
	public static long NGAYCOHIEULUC_COLUMN_BITMASK = 32L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.dtt.portal.dao.vbpq.model.VanBanPhapQuy"));

	public VanBanPhapQuyModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return VanBanPhapQuy.class;
	}

	@Override
	public String getModelClassName() {
		return VanBanPhapQuy.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("maVanBan", getMaVanBan());
		attributes.put("ngayTao", getNgayTao());
		attributes.put("ngaySua", getNgaySua());
		attributes.put("nguoiTao", getNguoiTao());
		attributes.put("nguoiSua", getNguoiSua());
		attributes.put("trichYeu", getTrichYeu());
		attributes.put("coQuanBanHanh", getCoQuanBanHanh());
		attributes.put("loaiVanBan", getLoaiVanBan());
		attributes.put("linhVucVanBan", getLinhVucVanBan());
		attributes.put("ngayBanHanh", getNgayBanHanh());
		attributes.put("ngayCoHieuLuc", getNgayCoHieuLuc());
		attributes.put("ngayHetHieuLuc", getNgayHetHieuLuc());
		attributes.put("nguoiKy", getNguoiKy());
		attributes.put("vanBanThayThe", getVanBanThayThe());
		attributes.put("groupId", getGroupId());
		attributes.put("status", getStatus());
		attributes.put("statusByDate", getStatusByDate());
		attributes.put("statusByUserId", getStatusByUserId());
		attributes.put("statusByUserName", getStatusByUserName());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String maVanBan = (String)attributes.get("maVanBan");

		if (maVanBan != null) {
			setMaVanBan(maVanBan);
		}

		Date ngayTao = (Date)attributes.get("ngayTao");

		if (ngayTao != null) {
			setNgayTao(ngayTao);
		}

		Date ngaySua = (Date)attributes.get("ngaySua");

		if (ngaySua != null) {
			setNgaySua(ngaySua);
		}

		String nguoiTao = (String)attributes.get("nguoiTao");

		if (nguoiTao != null) {
			setNguoiTao(nguoiTao);
		}

		String nguoiSua = (String)attributes.get("nguoiSua");

		if (nguoiSua != null) {
			setNguoiSua(nguoiSua);
		}

		String trichYeu = (String)attributes.get("trichYeu");

		if (trichYeu != null) {
			setTrichYeu(trichYeu);
		}

		Long coQuanBanHanh = (Long)attributes.get("coQuanBanHanh");

		if (coQuanBanHanh != null) {
			setCoQuanBanHanh(coQuanBanHanh);
		}

		Long loaiVanBan = (Long)attributes.get("loaiVanBan");

		if (loaiVanBan != null) {
			setLoaiVanBan(loaiVanBan);
		}

		Long linhVucVanBan = (Long)attributes.get("linhVucVanBan");

		if (linhVucVanBan != null) {
			setLinhVucVanBan(linhVucVanBan);
		}

		Date ngayBanHanh = (Date)attributes.get("ngayBanHanh");

		if (ngayBanHanh != null) {
			setNgayBanHanh(ngayBanHanh);
		}

		Date ngayCoHieuLuc = (Date)attributes.get("ngayCoHieuLuc");

		if (ngayCoHieuLuc != null) {
			setNgayCoHieuLuc(ngayCoHieuLuc);
		}

		Date ngayHetHieuLuc = (Date)attributes.get("ngayHetHieuLuc");

		if (ngayHetHieuLuc != null) {
			setNgayHetHieuLuc(ngayHetHieuLuc);
		}

		String nguoiKy = (String)attributes.get("nguoiKy");

		if (nguoiKy != null) {
			setNguoiKy(nguoiKy);
		}

		Long vanBanThayThe = (Long)attributes.get("vanBanThayThe");

		if (vanBanThayThe != null) {
			setVanBanThayThe(vanBanThayThe);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		Date statusByDate = (Date)attributes.get("statusByDate");

		if (statusByDate != null) {
			setStatusByDate(statusByDate);
		}

		Long statusByUserId = (Long)attributes.get("statusByUserId");

		if (statusByUserId != null) {
			setStatusByUserId(statusByUserId);
		}

		String statusByUserName = (String)attributes.get("statusByUserName");

		if (statusByUserName != null) {
			setStatusByUserName(statusByUserName);
		}
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@Override
	public String getMaVanBan() {
		if (_maVanBan == null) {
			return StringPool.BLANK;
		}
		else {
			return _maVanBan;
		}
	}

	@Override
	public void setMaVanBan(String maVanBan) {
		_columnBitmask |= MAVANBAN_COLUMN_BITMASK;

		if (_originalMaVanBan == null) {
			_originalMaVanBan = _maVanBan;
		}

		_maVanBan = maVanBan;
	}

	public String getOriginalMaVanBan() {
		return GetterUtil.getString(_originalMaVanBan);
	}

	@Override
	public Date getNgayTao() {
		return _ngayTao;
	}

	@Override
	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	@Override
	public Date getNgaySua() {
		return _ngaySua;
	}

	@Override
	public void setNgaySua(Date ngaySua) {
		_ngaySua = ngaySua;
	}

	@Override
	public String getNguoiTao() {
		if (_nguoiTao == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiTao;
		}
	}

	@Override
	public void setNguoiTao(String nguoiTao) {
		_nguoiTao = nguoiTao;
	}

	@Override
	public String getNguoiSua() {
		if (_nguoiSua == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiSua;
		}
	}

	@Override
	public void setNguoiSua(String nguoiSua) {
		_nguoiSua = nguoiSua;
	}

	@Override
	public String getTrichYeu() {
		if (_trichYeu == null) {
			return StringPool.BLANK;
		}
		else {
			return _trichYeu;
		}
	}

	@Override
	public void setTrichYeu(String trichYeu) {
		_trichYeu = trichYeu;
	}

	@Override
	public long getCoQuanBanHanh() {
		return _coQuanBanHanh;
	}

	@Override
	public void setCoQuanBanHanh(long coQuanBanHanh) {
		_columnBitmask |= COQUANBANHANH_COLUMN_BITMASK;

		if (!_setOriginalCoQuanBanHanh) {
			_setOriginalCoQuanBanHanh = true;

			_originalCoQuanBanHanh = _coQuanBanHanh;
		}

		_coQuanBanHanh = coQuanBanHanh;
	}

	public long getOriginalCoQuanBanHanh() {
		return _originalCoQuanBanHanh;
	}

	@Override
	public long getLoaiVanBan() {
		return _loaiVanBan;
	}

	@Override
	public void setLoaiVanBan(long loaiVanBan) {
		_loaiVanBan = loaiVanBan;
	}

	@Override
	public long getLinhVucVanBan() {
		return _linhVucVanBan;
	}

	@Override
	public void setLinhVucVanBan(long linhVucVanBan) {
		_linhVucVanBan = linhVucVanBan;
	}

	@Override
	public Date getNgayBanHanh() {
		return _ngayBanHanh;
	}

	@Override
	public void setNgayBanHanh(Date ngayBanHanh) {
		_columnBitmask = -1L;

		_ngayBanHanh = ngayBanHanh;
	}

	@Override
	public Date getNgayCoHieuLuc() {
		return _ngayCoHieuLuc;
	}

	@Override
	public void setNgayCoHieuLuc(Date ngayCoHieuLuc) {
		_columnBitmask = -1L;

		_ngayCoHieuLuc = ngayCoHieuLuc;
	}

	@Override
	public Date getNgayHetHieuLuc() {
		return _ngayHetHieuLuc;
	}

	@Override
	public void setNgayHetHieuLuc(Date ngayHetHieuLuc) {
		_ngayHetHieuLuc = ngayHetHieuLuc;
	}

	@Override
	public String getNguoiKy() {
		if (_nguoiKy == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiKy;
		}
	}

	@Override
	public void setNguoiKy(String nguoiKy) {
		_nguoiKy = nguoiKy;
	}

	@Override
	public long getVanBanThayThe() {
		return _vanBanThayThe;
	}

	@Override
	public void setVanBanThayThe(long vanBanThayThe) {
		_vanBanThayThe = vanBanThayThe;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (!_setOriginalStatus) {
			_setOriginalStatus = true;

			_originalStatus = _status;
		}

		_status = status;
	}

	public int getOriginalStatus() {
		return _originalStatus;
	}

	@Override
	public Date getStatusByDate() {
		return _statusByDate;
	}

	@Override
	public void setStatusByDate(Date statusByDate) {
		_statusByDate = statusByDate;
	}

	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getStatusByUserId(), "uuid",
			_statusByUserUuid);
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
		_statusByUserUuid = statusByUserUuid;
	}

	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return StringPool.BLANK;
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			VanBanPhapQuy.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public VanBanPhapQuy toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (VanBanPhapQuy)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VanBanPhapQuyImpl vanBanPhapQuyImpl = new VanBanPhapQuyImpl();

		vanBanPhapQuyImpl.setId(getId());
		vanBanPhapQuyImpl.setMaVanBan(getMaVanBan());
		vanBanPhapQuyImpl.setNgayTao(getNgayTao());
		vanBanPhapQuyImpl.setNgaySua(getNgaySua());
		vanBanPhapQuyImpl.setNguoiTao(getNguoiTao());
		vanBanPhapQuyImpl.setNguoiSua(getNguoiSua());
		vanBanPhapQuyImpl.setTrichYeu(getTrichYeu());
		vanBanPhapQuyImpl.setCoQuanBanHanh(getCoQuanBanHanh());
		vanBanPhapQuyImpl.setLoaiVanBan(getLoaiVanBan());
		vanBanPhapQuyImpl.setLinhVucVanBan(getLinhVucVanBan());
		vanBanPhapQuyImpl.setNgayBanHanh(getNgayBanHanh());
		vanBanPhapQuyImpl.setNgayCoHieuLuc(getNgayCoHieuLuc());
		vanBanPhapQuyImpl.setNgayHetHieuLuc(getNgayHetHieuLuc());
		vanBanPhapQuyImpl.setNguoiKy(getNguoiKy());
		vanBanPhapQuyImpl.setVanBanThayThe(getVanBanThayThe());
		vanBanPhapQuyImpl.setGroupId(getGroupId());
		vanBanPhapQuyImpl.setStatus(getStatus());
		vanBanPhapQuyImpl.setStatusByDate(getStatusByDate());
		vanBanPhapQuyImpl.setStatusByUserId(getStatusByUserId());
		vanBanPhapQuyImpl.setStatusByUserName(getStatusByUserName());

		vanBanPhapQuyImpl.resetOriginalValues();

		return vanBanPhapQuyImpl;
	}

	@Override
	public int compareTo(VanBanPhapQuy vanBanPhapQuy) {
		int value = 0;

		value = DateUtil.compareTo(getNgayBanHanh(),
				vanBanPhapQuy.getNgayBanHanh());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		value = DateUtil.compareTo(getNgayCoHieuLuc(),
				vanBanPhapQuy.getNgayCoHieuLuc());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof VanBanPhapQuy)) {
			return false;
		}

		VanBanPhapQuy vanBanPhapQuy = (VanBanPhapQuy)obj;

		long primaryKey = vanBanPhapQuy.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		VanBanPhapQuyModelImpl vanBanPhapQuyModelImpl = this;

		vanBanPhapQuyModelImpl._originalMaVanBan = vanBanPhapQuyModelImpl._maVanBan;

		vanBanPhapQuyModelImpl._originalCoQuanBanHanh = vanBanPhapQuyModelImpl._coQuanBanHanh;

		vanBanPhapQuyModelImpl._setOriginalCoQuanBanHanh = false;

		vanBanPhapQuyModelImpl._originalGroupId = vanBanPhapQuyModelImpl._groupId;

		vanBanPhapQuyModelImpl._setOriginalGroupId = false;

		vanBanPhapQuyModelImpl._originalStatus = vanBanPhapQuyModelImpl._status;

		vanBanPhapQuyModelImpl._setOriginalStatus = false;

		vanBanPhapQuyModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<VanBanPhapQuy> toCacheModel() {
		VanBanPhapQuyCacheModel vanBanPhapQuyCacheModel = new VanBanPhapQuyCacheModel();

		vanBanPhapQuyCacheModel.id = getId();

		vanBanPhapQuyCacheModel.maVanBan = getMaVanBan();

		String maVanBan = vanBanPhapQuyCacheModel.maVanBan;

		if ((maVanBan != null) && (maVanBan.length() == 0)) {
			vanBanPhapQuyCacheModel.maVanBan = null;
		}

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			vanBanPhapQuyCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			vanBanPhapQuyCacheModel.ngayTao = Long.MIN_VALUE;
		}

		Date ngaySua = getNgaySua();

		if (ngaySua != null) {
			vanBanPhapQuyCacheModel.ngaySua = ngaySua.getTime();
		}
		else {
			vanBanPhapQuyCacheModel.ngaySua = Long.MIN_VALUE;
		}

		vanBanPhapQuyCacheModel.nguoiTao = getNguoiTao();

		String nguoiTao = vanBanPhapQuyCacheModel.nguoiTao;

		if ((nguoiTao != null) && (nguoiTao.length() == 0)) {
			vanBanPhapQuyCacheModel.nguoiTao = null;
		}

		vanBanPhapQuyCacheModel.nguoiSua = getNguoiSua();

		String nguoiSua = vanBanPhapQuyCacheModel.nguoiSua;

		if ((nguoiSua != null) && (nguoiSua.length() == 0)) {
			vanBanPhapQuyCacheModel.nguoiSua = null;
		}

		vanBanPhapQuyCacheModel.trichYeu = getTrichYeu();

		String trichYeu = vanBanPhapQuyCacheModel.trichYeu;

		if ((trichYeu != null) && (trichYeu.length() == 0)) {
			vanBanPhapQuyCacheModel.trichYeu = null;
		}

		vanBanPhapQuyCacheModel.coQuanBanHanh = getCoQuanBanHanh();

		vanBanPhapQuyCacheModel.loaiVanBan = getLoaiVanBan();

		vanBanPhapQuyCacheModel.linhVucVanBan = getLinhVucVanBan();

		Date ngayBanHanh = getNgayBanHanh();

		if (ngayBanHanh != null) {
			vanBanPhapQuyCacheModel.ngayBanHanh = ngayBanHanh.getTime();
		}
		else {
			vanBanPhapQuyCacheModel.ngayBanHanh = Long.MIN_VALUE;
		}

		Date ngayCoHieuLuc = getNgayCoHieuLuc();

		if (ngayCoHieuLuc != null) {
			vanBanPhapQuyCacheModel.ngayCoHieuLuc = ngayCoHieuLuc.getTime();
		}
		else {
			vanBanPhapQuyCacheModel.ngayCoHieuLuc = Long.MIN_VALUE;
		}

		Date ngayHetHieuLuc = getNgayHetHieuLuc();

		if (ngayHetHieuLuc != null) {
			vanBanPhapQuyCacheModel.ngayHetHieuLuc = ngayHetHieuLuc.getTime();
		}
		else {
			vanBanPhapQuyCacheModel.ngayHetHieuLuc = Long.MIN_VALUE;
		}

		vanBanPhapQuyCacheModel.nguoiKy = getNguoiKy();

		String nguoiKy = vanBanPhapQuyCacheModel.nguoiKy;

		if ((nguoiKy != null) && (nguoiKy.length() == 0)) {
			vanBanPhapQuyCacheModel.nguoiKy = null;
		}

		vanBanPhapQuyCacheModel.vanBanThayThe = getVanBanThayThe();

		vanBanPhapQuyCacheModel.groupId = getGroupId();

		vanBanPhapQuyCacheModel.status = getStatus();

		Date statusByDate = getStatusByDate();

		if (statusByDate != null) {
			vanBanPhapQuyCacheModel.statusByDate = statusByDate.getTime();
		}
		else {
			vanBanPhapQuyCacheModel.statusByDate = Long.MIN_VALUE;
		}

		vanBanPhapQuyCacheModel.statusByUserId = getStatusByUserId();

		vanBanPhapQuyCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = vanBanPhapQuyCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			vanBanPhapQuyCacheModel.statusByUserName = null;
		}

		return vanBanPhapQuyCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(41);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", maVanBan=");
		sb.append(getMaVanBan());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", ngaySua=");
		sb.append(getNgaySua());
		sb.append(", nguoiTao=");
		sb.append(getNguoiTao());
		sb.append(", nguoiSua=");
		sb.append(getNguoiSua());
		sb.append(", trichYeu=");
		sb.append(getTrichYeu());
		sb.append(", coQuanBanHanh=");
		sb.append(getCoQuanBanHanh());
		sb.append(", loaiVanBan=");
		sb.append(getLoaiVanBan());
		sb.append(", linhVucVanBan=");
		sb.append(getLinhVucVanBan());
		sb.append(", ngayBanHanh=");
		sb.append(getNgayBanHanh());
		sb.append(", ngayCoHieuLuc=");
		sb.append(getNgayCoHieuLuc());
		sb.append(", ngayHetHieuLuc=");
		sb.append(getNgayHetHieuLuc());
		sb.append(", nguoiKy=");
		sb.append(getNguoiKy());
		sb.append(", vanBanThayThe=");
		sb.append(getVanBanThayThe());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", statusByDate=");
		sb.append(getStatusByDate());
		sb.append(", statusByUserId=");
		sb.append(getStatusByUserId());
		sb.append(", statusByUserName=");
		sb.append(getStatusByUserName());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(64);

		sb.append("<model><model-name>");
		sb.append("com.dtt.portal.dao.vbpq.model.VanBanPhapQuy");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maVanBan</column-name><column-value><![CDATA[");
		sb.append(getMaVanBan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngaySua</column-name><column-value><![CDATA[");
		sb.append(getNgaySua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiTao</column-name><column-value><![CDATA[");
		sb.append(getNguoiTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiSua</column-name><column-value><![CDATA[");
		sb.append(getNguoiSua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trichYeu</column-name><column-value><![CDATA[");
		sb.append(getTrichYeu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>coQuanBanHanh</column-name><column-value><![CDATA[");
		sb.append(getCoQuanBanHanh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiVanBan</column-name><column-value><![CDATA[");
		sb.append(getLoaiVanBan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>linhVucVanBan</column-name><column-value><![CDATA[");
		sb.append(getLinhVucVanBan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayBanHanh</column-name><column-value><![CDATA[");
		sb.append(getNgayBanHanh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayCoHieuLuc</column-name><column-value><![CDATA[");
		sb.append(getNgayCoHieuLuc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayHetHieuLuc</column-name><column-value><![CDATA[");
		sb.append(getNgayHetHieuLuc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiKy</column-name><column-value><![CDATA[");
		sb.append(getNguoiKy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>vanBanThayThe</column-name><column-value><![CDATA[");
		sb.append(getVanBanThayThe());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByDate</column-name><column-value><![CDATA[");
		sb.append(getStatusByDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserId</column-name><column-value><![CDATA[");
		sb.append(getStatusByUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserName</column-name><column-value><![CDATA[");
		sb.append(getStatusByUserName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = VanBanPhapQuy.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			VanBanPhapQuy.class
		};
	private long _id;
	private String _maVanBan;
	private String _originalMaVanBan;
	private Date _ngayTao;
	private Date _ngaySua;
	private String _nguoiTao;
	private String _nguoiSua;
	private String _trichYeu;
	private long _coQuanBanHanh;
	private long _originalCoQuanBanHanh;
	private boolean _setOriginalCoQuanBanHanh;
	private long _loaiVanBan;
	private long _linhVucVanBan;
	private Date _ngayBanHanh;
	private Date _ngayCoHieuLuc;
	private Date _ngayHetHieuLuc;
	private String _nguoiKy;
	private long _vanBanThayThe;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private int _status;
	private int _originalStatus;
	private boolean _setOriginalStatus;
	private Date _statusByDate;
	private long _statusByUserId;
	private String _statusByUserUuid;
	private String _statusByUserName;
	private long _columnBitmask;
	private VanBanPhapQuy _escapedModel;
}